In [127]:
import numpy as np

In [128]:
def removing_dominated_pure_strategies(m):
  # matrix size
  size = m.shape

  # return the matrix if it's already 1x1
  if size == (1,1):
    return m

  # check dominated rows
  for i in range(size[0]):
    for j in range(i + 1, size[0]):
      # compare these two rows
      result = (m[i,:] >= m[j,:])

      # if each elements in jth row >= to ith row
      # this implies that jth row dominate ith row
      if np.all(result == 0):
        # remove ith row
        # and continue looking for other dominated rows/columns
        m = np.delete(m,i,0)
        print("Row {} is (strongly) dominated by Row {}; \nThe new matrix is \n{}".format(i+1,j+1,m))
        return removing_dominated_strategies(m)

      # if each elements in jth row <= to ith row
      # this implies that ith row dominate jth row
      if np.all(result == 1):
        m = np.delete(m,j,0)
        print("Row {} is (strongly) dominated by Row {}; \nThe new matrix is \n{}".format(j+1,i+1,m))
        return removing_dominated_strategies(m)

  # check dominated columns
  for i in range(size[1]):
    for j in range(i + 1, size[1]):
      # compare these two columns
      result = (m[:,i] >= m[:,j])

      # if each elements in jth column >= to ith column
      # this implies that ith column dominate jth column
      if np.all(result == 0):
        # remove ith row
        # and continue looking for other dominated rows/columns
        m = np.delete(m,j,1)
        print("Column {} is (strongly) dominated by Column {}; \nThe new matrix is \n{}".format(j+1,i+1,m))
        return removing_dominated_strategies(m)

      # if each elements in jth row <= to ith row
      # this implies that jth row dominate ith row
      if np.all(result == 1):
        m = np.delete(m,i,1)
        print("Column {} is (strongly) dominated by Column {}; \nThe new matrix is \n{}".format(i+1,j+1,m))
        return removing_dominated_strategies(m)
  # if no dominated rows/column found
  return 

  

In [129]:
m1 = np.array([[1,5,-1,3], [3,4,1,-1],[1,-1,0,-2], [-1,0,3,1]])

In [130]:
print(m1)
removing_dominated_pure_strategies(m1)

[[ 1  5 -1  3]
 [ 3  4  1 -1]
 [ 1 -1  0 -2]
 [-1  0  3  1]]
Row 3 is (strongly) dominated by Row 2; 
The new matrix is 
[[ 1  5 -1  3]
 [ 3  4  1 -1]
 [-1  0  3  1]]
Column 2 is (strongly) dominated by Column 1; 
The new matrix is 
[[ 1 -1  3]
 [ 3  1 -1]
 [-1  3  1]]


In [131]:
m2 = np.array([[5,4,1,0], [4,3,2,-1],[0,-1,4,3], [1,-2,1,2]])

In [132]:
print(m2)
removing_dominated_pure_strategies(m2)

[[ 5  4  1  0]
 [ 4  3  2 -1]
 [ 0 -1  4  3]
 [ 1 -2  1  2]]
Column 1 is (strongly) dominated by Column 2; 
The new matrix is 
[[ 4  1  0]
 [ 3  2 -1]
 [-1  4  3]
 [-2  1  2]]
Row 4 is (strongly) dominated by Row 3; 
The new matrix is 
[[ 4  1  0]
 [ 3  2 -1]
 [-1  4  3]]
Column 2 is (strongly) dominated by Column 3; 
The new matrix is 
[[ 4  0]
 [ 3 -1]
 [-1  3]]
Row 2 is (strongly) dominated by Row 1; 
The new matrix is 
[[ 4  0]
 [-1  3]]
